# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Knot < Formula
  desc "A lightweight, configurable dotfiles manager"
  homepage "https://github.com/oxGrad/knot"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oxGrad/knot/releases/download/v0.1.0/knot_0.1.0_darwin_amd64.tar.gz"
      sha256 "2e27d0c9f815d7fced59956973b4009a1b1fc2811d70985e9bc0cce540cbfd26"

      define_method(:install) do
        bin.install "knot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oxGrad/knot/releases/download/v0.1.0/knot_0.1.0_darwin_arm64.tar.gz"
      sha256 "b0bd08d5a6aa027215d0f4174951cfd1995280abe0fe00a2da775312988e8625"

      define_method(:install) do
        bin.install "knot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oxGrad/knot/releases/download/v0.1.0/knot_0.1.0_linux_amd64.tar.gz"
      sha256 "a72bc400becf40fc35b1e88b0ec0aa64b041112f27ab9d7c18a0074b7d41e388"
      define_method(:install) do
        bin.install "knot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oxGrad/knot/releases/download/v0.1.0/knot_0.1.0_linux_arm64.tar.gz"
      sha256 "dc880a78b24f4ddfd39cf6b6ed2189a9d81fa78125ac001bc035eb4694b1aabb"
      define_method(:install) do
        bin.install "knot"
      end
    end
  end

  test do
    system "#{bin}/knot", "--help"
  end
end
