# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Knot < Formula
  desc "A lightweight, configurable dotfiles manager"
  homepage "https://github.com/oxGrad/knot"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oxGrad/knot/releases/download/v0.5.0/knot_0.5.0_darwin_amd64.tar.gz"
      sha256 "20543f6759f7dce3fd0b5f2e4b70ecbd0bc5d57d8ed71a45dd74c828aa098fc3"

      define_method(:install) do
        bin.install "knot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oxGrad/knot/releases/download/v0.5.0/knot_0.5.0_darwin_arm64.tar.gz"
      sha256 "21beaba518efa906123fa92519abdc56fc36f8e16aeab80e348a17bd8d5bcd65"

      define_method(:install) do
        bin.install "knot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oxGrad/knot/releases/download/v0.5.0/knot_0.5.0_linux_amd64.tar.gz"
      sha256 "3564defbc3e94caaa1c42427176a769f82d3b1ba900d582785a106d211ceceff"
      define_method(:install) do
        bin.install "knot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oxGrad/knot/releases/download/v0.5.0/knot_0.5.0_linux_arm64.tar.gz"
      sha256 "9d754ee917d4a6dd14df94d5849a5336d083475c3d40c97e4274cd3138493d90"
      define_method(:install) do
        bin.install "knot"
      end
    end
  end
end
