# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skein < Formula
  desc "Claude Code statusline: model, context/plan usage bars, caveman badge"
  homepage "https://github.com/oxGrad/skein"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oxGrad/skein/releases/download/v1.0.0/skein_1.0.0_darwin_amd64.tar.gz"
      sha256 "09656f58c9ba8f4f8546836bb6bb1d28a3e5f1d93341f7cdfd2674027c385fe8"

      define_method(:install) do
        bin.install "skein"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oxGrad/skein/releases/download/v1.0.0/skein_1.0.0_darwin_arm64.tar.gz"
      sha256 "59004a0a904dcfc646f02ff3ad18b4979862f9da61b1e71beb2b50c8778434cc"

      define_method(:install) do
        bin.install "skein"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oxGrad/skein/releases/download/v1.0.0/skein_1.0.0_linux_amd64.tar.gz"
      sha256 "95de00eabf5332277f2a8f636574a13928ccedab6c1364a150706adaf16a6f23"
      define_method(:install) do
        bin.install "skein"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oxGrad/skein/releases/download/v1.0.0/skein_1.0.0_linux_arm64.tar.gz"
      sha256 "db8f2ff608806c4aa865b25348f3c19fe0f58b09240ec3c795116c1992f05968"
      define_method(:install) do
        bin.install "skein"
      end
    end
  end
end
