# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spicebag < Formula
  desc "Season every application perfectly — CV and cover letter manager for Claude Code"
  homepage "https://github.com/oxGrad/spicebag"
  version "0.9.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oxGrad/spicebag/releases/download/v0.9.3/spicebag_0.9.3_darwin_amd64.tar.gz"
      sha256 "9e33d0bcbcc618dd8b71b12d4b511a5ad36a45f9a661bce0a274a69287248a4c"

      define_method(:install) do
        bin.install "spicebag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oxGrad/spicebag/releases/download/v0.9.3/spicebag_0.9.3_darwin_arm64.tar.gz"
      sha256 "5ae1fdf04b877618f53c64141ee9a0d2f5174ce1fe6c9465426563bf106d9ef4"

      define_method(:install) do
        bin.install "spicebag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oxGrad/spicebag/releases/download/v0.9.3/spicebag_0.9.3_linux_amd64.tar.gz"
      sha256 "15541639e7811bb464369b6db7423e246b2f7e5c80f633b934f8037316207f45"
      define_method(:install) do
        bin.install "spicebag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oxGrad/spicebag/releases/download/v0.9.3/spicebag_0.9.3_linux_arm64.tar.gz"
      sha256 "90c6ab604babdfe613815780afbf059fcd2544f7316590e1151317489e7db0e8"
      define_method(:install) do
        bin.install "spicebag"
      end
    end
  end
end
