# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spicebag < Formula
  desc "Season every application perfectly — CV and cover letter manager for Claude Code"
  homepage "https://github.com/oxGrad/spicebag"
  version "0.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oxGrad/spicebag/releases/download/v0.8.1/spicebag_0.8.1_darwin_amd64.tar.gz"
      sha256 "0e5e2f853ba5c0cfeca10cdbe5b691bdb5a5dd700568407a90f8e43fcf11d78d"

      define_method(:install) do
        bin.install "spicebag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oxGrad/spicebag/releases/download/v0.8.1/spicebag_0.8.1_darwin_arm64.tar.gz"
      sha256 "b16dfe4dfea08a6d77925d01a0af6d7f53cc1ebdc2f31132c4d001372078c92c"

      define_method(:install) do
        bin.install "spicebag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oxGrad/spicebag/releases/download/v0.8.1/spicebag_0.8.1_linux_amd64.tar.gz"
      sha256 "47906fbae080a0bffea69ba2a7fe9569f50afd211be43d95f1d41e7d2f431ea7"
      define_method(:install) do
        bin.install "spicebag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oxGrad/spicebag/releases/download/v0.8.1/spicebag_0.8.1_linux_arm64.tar.gz"
      sha256 "ef77c1fd2fc84e86069c99c0ef7629b673df85fafa56ba29ad5ccfc0bb661888"
      define_method(:install) do
        bin.install "spicebag"
      end
    end
  end
end
