# This file was generated by GoReleaser. DO NOT EDIT.
cask "knot" do
  version "0.1.0-nightly.20260404"

  on_macos do
    on_intel do
      url "https://github.com/oxGrad/knot/releases/download/v#{version}/knot_#{version}_darwin_amd64.tar.gz"
      sha256 "869b65a21c1fcedab1d2da5f4388907b2fae83f09a4c07b7fe82d35bd245d8d7"
    end
    on_arm do
      url "https://github.com/oxGrad/knot/releases/download/v#{version}/knot_#{version}_darwin_arm64.tar.gz"
      sha256 "e547f0f91cbfc6d90e90e833537efb019ede25bc430740f024fa570366e98f6f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oxGrad/knot/releases/download/v#{version}/knot_#{version}_linux_amd64.tar.gz"
      sha256 "2a7748462c0e4e63deb0b98cc30807ff89a0cfef919a00c6f4ae3b5eb7c157dd"
    end
    on_arm do
      url "https://github.com/oxGrad/knot/releases/download/v#{version}/knot_#{version}_linux_arm64.tar.gz"
      sha256 "fc4225ee7a1af17eb3c33769400321f4b249311ef0dcc44d3e8b5c3fb5b8ed59"
    end
  end

  name "knot"
  desc "A lightweight, configurable dotfiles manager"
  homepage "https://github.com/oxGrad/knot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "knot"

  # No zap stanza required

end
