# This file was generated by GoReleaser. DO NOT EDIT.
cask "knot" do
  version "0.2.0-nightly.20260404"

  on_macos do
    on_intel do
      url "https://github.com/oxGrad/knot/releases/download/v#{version}/knot_#{version}_darwin_amd64.tar.gz"
      sha256 "2365c9d25fff75cdcde184b836a5a65e6641c6f80a948702bd4fa9b4cbd6ce7d"
    end
    on_arm do
      url "https://github.com/oxGrad/knot/releases/download/v#{version}/knot_#{version}_darwin_arm64.tar.gz"
      sha256 "6520286a06e1891f1cd396dd2c0b00d7afeacbbfbb09992a788446f91c023879"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oxGrad/knot/releases/download/v#{version}/knot_#{version}_linux_amd64.tar.gz"
      sha256 "6ecca9681aa113ff87d93c0947b78e00d9fab8a6b809d7025a032c70fd3c5d2d"
    end
    on_arm do
      url "https://github.com/oxGrad/knot/releases/download/v#{version}/knot_#{version}_linux_arm64.tar.gz"
      sha256 "2186dae2ec4668e93fb19a4615c4c4ead2155f3f779843a0e867e8c0079341c9"
    end
  end

  name "knot"
  desc "A lightweight, configurable dotfiles manager"
  homepage "https://github.com/oxGrad/knot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "knot"

  # No zap stanza required

end
